auth/urls.py
from django.conf.urls import url

from . import views

app_name = 'auth'

urlpatterns = [
	url(r'^$',views.index,name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signout/$',views.signout,name='logout'),
]

authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [
	url(r'^$',views.index,name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signout/$',views.signout,name='logout'),
]

textnook/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   	#url(r'^',include('predict.urls' , namespace = 'predict')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authentication/',include('authentication.urls',namespace='authentication')),
    url(r'^learn/',include('learn.urls',namespace='learn')),
    url(r'^predict/',include('predict.urls',namespace='predict')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
)

authentication/models.py
from django.db import models

authentication/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.contrib.auth.models import User
import json
# Create your views here.

def index(request):

	if request.user.is_authenticated() and request.user.is_active == True:
		return redirect('/learn')
	else:
		return redirect('/authentication/signin')



def signout(request):
	#print "logging out" this also clears all session data
	logout(request) 
	return redirect('/authentication/')


def signin(request):
	if request.user.is_authenticated() == True and request.user.is_active == True:
		return redirect('/learn')
	if request.method == 'POST':
		print "post"
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user is None:
			return render(request,'authentication/signin.html',{'error':'Invalid username or password'})
		
		login(request,user)
		return redirect('/learn/') #render the learn page
	else:
		print "no post"
		return render(request,'authentication/signin.html',None)

def signup(request):
	if request.user.is_authenticated() == True and request.user.is_active == True:
		return redirect('/learn')
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		password2 = request.POST['password2']
		firstName = request.POST['firstName']
		lastName = request.POST['lastName']
		if password2 != password:
			return render(request,'authentication/signup.html',{'error':'Password doesn\'t match'}) 

		emailAddr = request.POST['email']

		try:
			u = User._default_manager.get(username__iexact=username) #fix for case sensitive username
			return render(request,'authentication/signup.html',{'error':'username already already exists!'})
		except User.DoesNotExist:
			user = User.objects.create_user(username=username,email=emailAddr,first_name=firstName,last_name=lastName)
			user.set_password(password)
			user.is_active = True #user will be active only when he completes registration
			user.is_staff=True
			user.is_superuser=True
			user.save()
			user.backend = 'django.contrib.auth.backends.ModelBackend' #user backend error fix
			authenticate(username=username,password=password)
			login(request,user)
			return redirect('/authentication')
	else:
		return render(request,'authentication/signup.html',None)

templates/authentication/signin.html
{% extends 'base/base.html' %}
{% block title %}
Login - Textnook Admin
{% endblock %}

{% block content %}
{% if error  %}
  <div class="chip">
    <div class = "material-icons">error_outline</div>{{error}}
    <i class="material-icons">close</i>
  </div>
{% endif %}
<div class = "row">
	<form class = "col s12" action = "{% url 'authentication:signin' %}" method = "post">
		{% csrf_token %}
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "username" required="">
				<label for="first_name">Username</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password" required="">
				<label for="first_name">password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s6">
				<input type="submit" class="validate btn green darken-4" name = "Sign up">
			</div>
		</div>
	</form>
</div>
<div class = "row">
	<a href = "{% url 'authentication:signup'%}">Signup!</a>
</div>
{% endblock %}

templates/authentication/signup.html
{% extends 'base/base.html' %}
{% block title %}
Signup - Textnook Admin
{% endblock %}

{% block content %}
{% if error  %}
  <div class="chip">
    <div class = "material-icons">error_outline</div>{{error}}
    <i class="material-icons">close</i>
  </div>
{% endif %}
<div class = "row">
	<form class = "col s12" action = "{% url 'authentication:signup' %}" method = "post">
		{% csrf_token %}
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "username" required="">
				<label for="first_name">Username</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "firstName" required="">
				<label for="first_name">First Name</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "lastName" required="">
				<label for="first_name">Last Name</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password" required="">
				<label for="first_name">password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password2" required="">
				<label for="first_name">Re-type password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="email" class="validate" name = "email" required="">
				<label for="first_name">email-address</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s6">
				<input type="submit" class="validate btn green darken-4" name = "Sign up">
			</div>
		</div>
	</form>
</div>
{% endblock %}